apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
        - name: myapps
          image: myapps:1.0.0
          ports:
            - containerPort: 3000